swagger: "2.0"
info:
  description: "This is a sample server Bot Framework server."
  version: "1.0.0"
  title: "My Bot"
  contact:
    email: "jdnichollsc@hotmail.com"
host: "mybot.mydomain.com"
basePath: "/api"
tags:
- name: "messages"
  description: "Comunication with the bot"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/proyecto26/Bot-Framework"
- name: "users"
  description: "Other endpoints of my service"
schemes:
- "http"
paths:
  /messages:
    post:
      tags:
      - "messages"
      summary: "Listen for messages from users"
      description: ""
      operationId: "bot"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Message sent"
  /users:
    get:
      tags:
      - "users"
      summary: "List the users"
      description: ""
      operationId: "getUsers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"